language: cpp
compiler:
  - gcc
cache: apt
before_install:
  - sudo apt-get -yqq update    #< Suggested by the Travis CI doc
  - sudo apt-get -fyq install   #< Fixes inconsistency of packages installed previously
install:
  - sudo apt-get -yq install build-essential chrpath libssl-dev libfontconfig1-dev  #< Build Dependencies
before_script:
  - chmod +x ./build.sh
  - chmod +x ./test/run-tainted-tests.sh
script:
  - ./build.sh --confirm --silent   #< Build
  - ./test/run-tainted-tests.js     #< Test (PhantomJS)
